language: node_js
node_js:
  - 12
cache:
  directories:
  - node_modules
script:
  - npm run build
  - npm run export
  - touch out/.nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token # GitHub access token to use when pushing to the gh-pages branch
  local_dir: out
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(master|main)$
